### ISSUE TITLE
Can't compile on ubuntu 15.10

### ISSUE THREAD

**Issue by c64zottel** [tklab-tud/uscxml#70]
Hello,

I just updated to Ubuntu 15.10 and can't compile uscxml:

[ 73%] Built target uscxml
[ 73%] Built target uscxml_transform
Scanning dependencies of target uscxml-analyze
[ 73%] Building CXX object CMakeFiles/uscxml-analyze.dir/apps/uscxml-analyze.cpp.o
Linking CXX executable bin/uscxml-analyze
CMakeFiles/uscxml-analyze.dir/apps/uscxml-analyze.cpp.o: In function `main':
uscxml-analyze.cpp:(.text.startup+0x41c): undefined reference to `Arabica::io::URI::as_string[abi:cxx11]() const'
lib/libuscxml64.so: undefined reference to `Arabica::io::URI::URI(Arabica::io::URI const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
lib/libuscxml64.so: undefined reference to `google::LogSink::ToString[abi:cxx11](int, char const*, int, tm const*, char const*, unsigned long)'
lib/libuscxml64.so: undefined reference to `Arabica::io::URI::URI(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
lib/libuscxml64.so: undefined reference to `Arabica::SAX::InputSourceResolver::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::istream*)'
lib/libuscxml64.so: undefined reference to `Arabica::io::URI::port[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
CMakeFiles/uscxml-analyze.dir/build.make:126: recipe for target 'bin/uscxml-analyze' failed
make[2]: *** [bin/uscxml-analyze] Error 1
CMakeFiles/Makefile2:189: recipe for target 'CMakeFiles/uscxml-analyze.dir/all' failed
make[1]: *** [CMakeFiles/uscxml-analyze.dir/all] Error 2
Makefile:146: recipe for target 'all' failed
make: *** [all] Error 2

I can't even find the place in uscxml where Arabica::io::URI::URI   is even used.
The error is not in the application, it is somewhere inside uscxml.

I appreciate any help.

Andreas

**Comment by sradomski** [comment]
I assume that this is an ABI compatibility issue with the C++ compiler on Ubuntu. In fact, I am just about to upload a new version of uscxml wherein Arabica was replaced by xerces-c and deprecate the current branch.
