### ISSUE TITLE
Compiling on Ubuntu 22.04 fails

### ISSUE THREAD

**Issue by larry104** [tklab-tud/uscxml#206]
When trying to compile on ubuntu 22.04 I get the following error:
` 59%] Linking CXX executable bin/uscxml-transform

/usr/bin/ld: lib/libuscxml_transform.so.2.0.3: undefined reference to `uscxml::PromelaParser::~PromelaParser()'

/usr/bin/ld: lib/libuscxml_transform.so.2.0.3: undefined reference to `uscxml::PromelaParserNode::dump(unsigned long)'

/usr/bin/ld: lib/libuscxml_transform.so.2.0.3: undefined reference to `uscxml::PromelaParser::PromelaParser(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

collect2: error: ld returned 1 exit status

make[2]: *** [CMakeFiles/uscxml-transform.dir/build.make:126: bin/uscxml-transform] Error 1

make[1]: *** [CMakeFiles/Makefile2:367: CMakeFiles/uscxml-transform.dir/all] Error 2

make: *** [Makefile:166: all] Error 2`

Any idea how to solve that?

**Comment by alexzhornyak** [comment]
1. You are trying to compile uscxml-transform application. It transfroms scxml state chart into C code. I am not sure that you need it. But if you need, you should enable Promela in Cmake and convince that Promela is installed on your system

![image](https://github.com/tklab-tud/uscxml/assets/18611095/7946346c-ec9d-45fe-9464-3ea371c23b6b)

2. I think that you need only SCXML library functions, in this case it will be enough to build only xerces, libevent, uscxml and uscxml-browser

![image](https://github.com/tklab-tud/uscxml/assets/18611095/0f1ab944-7104-482e-95f4-1590dc193f32)

**Comment by larry104** [comment]
yes, you are right if I just compile parts of it it compiles without error. Let me try to run some example if I get it to work.
Thanks again for your help!

**Comment by larry104** [comment]
When just building the targets uscxml and uscxml-browser I can't seem to find anywhere a package file so that qt6.x cmake knows with find_package(USCXML .. ) how to link and include the headers. Do I miss something here? At least I was able to manually compile and link a simple example though.

**Comment by larry104** [comment]
So, I finally got it to work that I can compile and run a state machine with an ecmascript datamodel. Can anyone point me to a simple example how to send and receive events?

**Comment by alexzhornyak** [comment]
You can use as origin [this example](https://github.com/tklab-tud/uscxml/blob/master/test/src/test-state-pass.cpp)

**1. Here you can see how to subscribe to different state machine events**

![image](https://github.com/tklab-tud/uscxml/assets/18611095/2e7cfa45-3a9e-41f2-8c8b-b75230aaab4f)

![image](https://github.com/tklab-tud/uscxml/assets/18611095/ccf6954a-5bbd-4833-8b0b-cc2853e5ec1f)

**2. Here is an example how to pass event to state machine**

![image](https://github.com/tklab-tud/uscxml/assets/18611095/228fa8bb-0c6a-40e7-9311-f80817d1f93a)

**Comment by larry104** [comment]
Thanks! That helps a lot.
